# Generated by Django 5.0.4 on 2024-04-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_principal_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
