# Generated by Django 5.0.4 on 2024-04-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_principal_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
