# Generated by Django 4.2.11 on 2024-04-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0003_currencyrates_remove_account_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="transaction", name="amount",),
        migrations.AddField(
            model_name="transaction",
            name="receiver_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="transaction",
            name="receiver_currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="transaction",
            name="sender_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="transaction",
            name="sender_currency",
            field=models.CharField(default="USD", max_length=3),
        ),
    ]
