# Generated by Django 4.2.11 on 2024-04-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0004_remove_transaction_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="amountrequest",
            name="requester_currency",
            field=models.CharField(default="USD", max_length=3),
        ),
    ]
